[11/Apr/2019 12:50:10] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 12:50:20] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 12:50:22] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 12:50:33] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 12:50:36] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 12:50:37] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 12:51:47] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 12:51:49] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 12:53:37] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 12:53:39] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 12:53:43] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 12:53:50] "GET /blog/article/12/ HTTP/1.1" 200 342
Not Found: /blog/admin
[11/Apr/2019 12:54:14] "GET /blog/admin HTTP/1.1" 404 3326
[11/Apr/2019 12:54:20] "GET /admin HTTP/1.1" 301 0
[11/Apr/2019 12:54:20] "GET /admin/ HTTP/1.1" 302 0
[11/Apr/2019 12:54:20] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1819
[11/Apr/2019 12:54:20] "GET /static/admin/css/base.css HTTP/1.1" 200 16225
[11/Apr/2019 12:54:20] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[11/Apr/2019 12:54:20] "GET /static/admin/css/responsive.css HTTP/1.1" 200 17976
[11/Apr/2019 12:54:20] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[11/Apr/2019 12:54:20] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[11/Apr/2019 12:54:20] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[11/Apr/2019 12:54:27] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[11/Apr/2019 12:54:27] "GET /admin/ HTTP/1.1" 200 5116
[11/Apr/2019 12:54:27] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[11/Apr/2019 12:54:27] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[11/Apr/2019 12:54:28] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[11/Apr/2019 12:54:28] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[11/Apr/2019 12:54:28] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[11/Apr/2019 12:54:29] "GET /admin/blog/article/ HTTP/1.1" 200 4800
[11/Apr/2019 12:54:29] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[11/Apr/2019 12:54:29] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[11/Apr/2019 12:54:29] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[11/Apr/2019 12:54:29] "GET /static/admin/js/core.js HTTP/1.1" 200 7135
[11/Apr/2019 12:54:29] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6918
[11/Apr/2019 12:54:29] "GET /static/admin/js/actions.js HTTP/1.1" 200 6538
[11/Apr/2019 12:54:29] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8972
[11/Apr/2019 12:54:29] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1530
[11/Apr/2019 12:54:30] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[11/Apr/2019 12:54:30] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 271751
[11/Apr/2019 12:54:30] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[11/Apr/2019 12:54:32] "GET /admin/blog/article/3/change/ HTTP/1.1" 200 4853
[11/Apr/2019 12:54:32] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[11/Apr/2019 12:54:32] "GET /static/admin/css/forms.css HTTP/1.1" 200 8505
[11/Apr/2019 12:54:32] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
[11/Apr/2019 12:54:32] "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
[11/Apr/2019 12:54:32] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
[11/Apr/2019 12:54:34] "GET /admin/blog/article/ HTTP/1.1" 200 4800
[11/Apr/2019 12:54:35] "GET /admin/blog/article/2/change/ HTTP/1.1" 200 4862
[11/Apr/2019 12:54:35] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[11/Apr/2019 12:54:37] "GET /admin/blog/article/ HTTP/1.1" 200 4800
[11/Apr/2019 12:54:38] "GET /admin/blog/article/12/change/ HTTP/1.1" 200 4791
[11/Apr/2019 12:54:39] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[11/Apr/2019 12:54:43] "GET /admin/blog/article/ HTTP/1.1" 200 4800
[11/Apr/2019 13:00:25] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 13:00:26] "GET /blog/edit/tocha/3/ HTTP/1.1" 200 704
[11/Apr/2019 13:10:19] "GET /blog/edit/ HTTP/1.1" 200 552
[11/Apr/2019 13:10:34] "POST /blog/edit/action/ HTTP/1.1" 200 644
[11/Apr/2019 13:10:45] "GET /blog/article/14/ HTTP/1.1" 200 263
[11/Apr/2019 13:10:47] "GET /blog/edit/tocha/14/ HTTP/1.1" 200 567
[11/Apr/2019 13:10:52] "POST /blog/edit/change/14/ HTTP/1.1" 200 644
[11/Apr/2019 13:10:56] "GET /blog/article/14/ HTTP/1.1" 200 270
[11/Apr/2019 13:10:57] "GET /blog/index/ HTTP/1.1" 200 644
[11/Apr/2019 13:10:59] "GET /blog/article/14/ HTTP/1.1" 200 270
[11/Apr/2019 13:11:01] "GET /blog/index/ HTTP/1.1" 200 644
[11/Apr/2019 13:11:02] "GET /blog/article/14/ HTTP/1.1" 200 270
[11/Apr/2019 13:11:04] "GET /blog/edit/tocha/14/ HTTP/1.1" 200 574
[11/Apr/2019 13:11:09] "POST /blog/edit/change/14/ HTTP/1.1" 200 653
[11/Apr/2019 13:11:10] "GET /blog/article/14/ HTTP/1.1" 200 279
[11/Apr/2019 13:11:12] "GET /blog/index/ HTTP/1.1" 200 653
[11/Apr/2019 13:11:13] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 13:11:14] "GET /blog/index/ HTTP/1.1" 200 653
[11/Apr/2019 13:11:16] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 13:11:17] "GET /blog/edit/tocha/3/ HTTP/1.1" 200 704
[11/Apr/2019 13:11:20] "POST /blog/edit/change/3/ HTTP/1.1" 200 653
[11/Apr/2019 13:11:23] "GET /blog/edit/ HTTP/1.1" 200 552
[11/Apr/2019 13:11:30] "GET /blog/article/14/ HTTP/1.1" 200 279
[11/Apr/2019 13:15:42] "GET /blog/edit/delete/14/ HTTP/1.1" 200 540
[11/Apr/2019 14:50:38] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 14:50:39] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 14:51:34] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 14:51:37] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 14:51:41] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 14:51:44] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 15:01:36] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 15:01:44] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 15:01:45] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 15:01:46] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 15:01:47] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 15:01:51] "GET /blog/index/ HTTP/1.1" 200 540
[11/Apr/2019 15:04:32] "GET /blog/index/?nsukey=VXTtA3jZKIURu7lYqTRehOpCeP4hTWDdTwkETy9lDDl%2FIrz6v8UT6qROZQQSIGVkcbGkP5d5IrKHHQ%2B06aKqsPI5k4jYXJNYoOBvwpCJ7mBsyr7AEgx1rIONSf7v%2BQC0ucrnOs1a%2BHZYB98XcJFTHLLx4A5GE16B6eWCad1IDXlBLe6946El%2Fof9AbChSW6UwBtwNUtDvAWfSQvWvP%2FTjQ%3D%3D HTTP/1.1" 200 540
[11/Apr/2019 15:04:35] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 15:04:36] "GET /blog/article/2/?nsukey=2pmIF6FS5mWd6edyVCLP85NfmR1Z26kZHGWsJvjs0xZZ0rUQwyhLdUXI3fanZTlkCjrwM3N3uU%2FqSwFyI8ggsDpW2OcudPdI3qiweJLV%2BLXKMy6omHVfzbEo%2Fwb%2F%2BkOXLAsbbJ%2FspUMFjCvsR0rmsRGoBx5C0sWKwUNh65BdaPgrI2M%2BYGASd0fN66pW9dQYwr%2BbNWpx1Vj7Hf9g3r%2B0Mg%3D%3D HTTP/1.1" 200 409
----------------------------------------
Exception happened during processing of request from ('220.112.121.253', 50115)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Apr/2019 15:05:30] "GET /blog/index HTTP/1.1" 301 0
[11/Apr/2019 15:05:32] "GET /blog/index/?nsukey=VXTtA3jZKIURu7lYqTRehOpCeP4hTWDdTwkETy9lDDl%2FIrz6v8UT6qROZQQSIGVkcbGkP5d5IrKHHQ%2B06aKqsPI5k4jYXJNYoOBvwpCJ7mBsyr7AEgx1rIONSf7v%2BQC0ucrnOs1a%2BHZYB98XcJFTHLLx4A5GE16B6eWCad1IDXlBLe6946El%2Fof9AbChSW6UwBtwNUtDvAWfSQvWvP%2FTjQ%3D%3D HTTP/1.1" 200 540
[11/Apr/2019 15:05:35] "GET /blog/article/2 HTTP/1.1" 301 0
[11/Apr/2019 15:05:36] "GET /blog/article/2/?nsukey=2pmIF6FS5mWd6edyVCLP85NfmR1Z26kZHGWsJvjs0xZZ0rUQwyhLdUXI3fanZTlkCjrwM3N3uU%2FqSwFyI8ggsDpW2OcudPdI3qiweJLV%2BLXKMy6omHVfzbEo%2Fwb%2F%2BkOXLAsbbJ%2FspUMFjCvsR0rmsRGoBx5C0sWKwUNh65BdaPgrI2M%2BYGASd0fN66pW9dQYwr%2BbNWpx1Vj7Hf9g3r%2B0Mg%3D%3D HTTP/1.1" 200 409
[11/Apr/2019 15:39:00] "GET /blog/index/ HTTP/1.1" 200 626
[11/Apr/2019 15:41:11] "GET /blog/index/ HTTP/1.1" 200 642
[11/Apr/2019 15:42:03] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 15:42:06] "GET /blog/edit/ HTTP/1.1" 200 552
[11/Apr/2019 15:42:11] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 15:42:17] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 15:43:21] "GET /blog/index/?nsukey=whiCJUlKDHHxrAsSC3ExBv%2BhSy7pSoCREl2DNS6JwsGBw9zCfx99TA8Rzy6XgRIIJLDgHhDcBUviD1qvqxuzABgYdth7%2Fc%2Be3bfdPfKp0Hm2VTp1MUXRafh0KF%2BkILN8sgVvHP9HdTctnQWZLQG8hLr%2FY0Ez6Wr%2B8cDSk%2F3ARRH5cwXa%2BHWzrHlAsapTv%2F7bNZCQSDOaI6Q8KyyiiCxkSw%3D%3D HTTP/1.1" 200 642
----------------------------------------
Exception happened during processing of request from ('220.112.121.253', 50127)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Apr/2019 15:44:21] "GET /blog/index/?nsukey=whiCJUlKDHHxrAsSC3ExBv%2BhSy7pSoCREl2DNS6JwsGBw9zCfx99TA8Rzy6XgRIIJLDgHhDcBUviD1qvqxuzABgYdth7%2Fc%2Be3bfdPfKp0Hm2VTp1MUXRafh0KF%2BkILN8sgVvHP9HdTctnQWZLQG8hLr%2FY0Ez6Wr%2B8cDSk%2F3ARRH5cwXa%2BHWzrHlAsapTv%2F7bNZCQSDOaI6Q8KyyiiCxkSw%3D%3D HTTP/1.1" 200 642
[11/Apr/2019 16:06:35] "GET /blog/index/ HTTP/1.1" 200 642
[11/Apr/2019 16:06:38] "GET /blog/article/12/ HTTP/1.1" 200 342
[11/Apr/2019 16:06:44] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 16:06:46] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 16:06:49] "GET /blog/article/3/ HTTP/1.1" 200 400
[11/Apr/2019 16:08:02] "GET /blog/index/ HTTP/1.1" 200 642
[11/Apr/2019 16:08:06] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 16:08:10] "GET /blog/edit/ HTTP/1.1" 200 552
[11/Apr/2019 16:08:12] "POST /blog/edit/action/ HTTP/1.1" 200 740
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[11/Apr/2019 16:13:40] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 58390)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Apr/2019 16:34:39] "GET /blog/index/?nsukey=VR0v303ClYme%2BoyTd8NeINbcOg23i6Sm17tLC8YdmDZ0olNWQKN7Cl9fzdQwPltBJFPdWq2Wax8WOo79oWKlEnTdBdp2hQSP13J5tXgj8Ms2gWtVEPh3bZfieZ8ntLwB1kVgnmMkIpH%2F4tuzWTtwZXzgHMRarZhlvIBLXBX6iVpONauX%2Bta7HH5YjP3lm3xDIc6YGuLXKn2ZpfdnySSTbg%3D%3D HTTP/1.1" 200 740
[11/Apr/2019 16:34:43] "GET /blog/article/2/ HTTP/1.1" 200 409
[11/Apr/2019 16:34:44] "GET /blog/article/2/?nsukey=igk9jZ6wjbKFaaDN93cPlFYGJQKHc6nRzASyh42tdw0J%2B41URGJCbaEyUn0jQktzZALplkBHAgWn2LIXL9BHueDeWNVIOooky5DvJC4nStSUG0YzHgdDO%2FtzHt%2BpIIn5yfTJtF3Pvm17HRXvmeX3I4S3ZchHMM8%2FEdM7F5ILN6aKgcZHllwfBQsZe8%2Ftv9E2MEqVLZ%2FjGtfhFTyrA1Rrug%3D%3D HTTP/1.1" 200 409
----------------------------------------
Exception happened during processing of request from ('220.112.121.253', 50200)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[11/Apr/2019 16:35:39] "GET /blog/index/?nsukey=VR0v303ClYme%2BoyTd8NeINbcOg23i6Sm17tLC8YdmDZ0olNWQKN7Cl9fzdQwPltBJFPdWq2Wax8WOo79oWKlEnTdBdp2hQSP13J5tXgj8Ms2gWtVEPh3bZfieZ8ntLwB1kVgnmMkIpH%2F4tuzWTtwZXzgHMRarZhlvIBLXBX6iVpONauX%2Bta7HH5YjP3lm3xDIc6YGuLXKn2ZpfdnySSTbg%3D%3D HTTP/1.1" 200 740
[11/Apr/2019 16:35:44] "GET /blog/article/2/?nsukey=igk9jZ6wjbKFaaDN93cPlFYGJQKHc6nRzASyh42tdw0J%2B41URGJCbaEyUn0jQktzZALplkBHAgWn2LIXL9BHueDeWNVIOooky5DvJC4nStSUG0YzHgdDO%2FtzHt%2BpIIn5yfTJtF3Pvm17HRXvmeX3I4S3ZchHMM8%2FEdM7F5ILN6aKgcZHllwfBQsZe8%2Ftv9E2MEqVLZ%2FjGtfhFTyrA1Rrug%3D%3D HTTP/1.1" 200 409
[12/Apr/2019 01:57:26] "GET /blog/index/ HTTP/1.1" 200 740
Not Found: /favicon.ico
[12/Apr/2019 01:57:27] "GET /favicon.ico HTTP/1.1" 404 2081
[12/Apr/2019 01:57:47] "GET /blog/edit/delete/15/ HTTP/1.1" 200 642
[12/Apr/2019 01:57:53] "GET /blog/article/12/ HTTP/1.1" 200 342
[12/Apr/2019 01:57:56] "GET /blog/index/ HTTP/1.1" 200 642
[12/Apr/2019 01:57:58] "GET /blog/article/2/ HTTP/1.1" 200 409
[12/Apr/2019 01:58:09] "GET /blog/edit/ HTTP/1.1" 200 552
[12/Apr/2019 01:58:10] "POST /blog/edit/action/ HTTP/1.1" 200 740
[12/Apr/2019 01:58:13] "GET /blog/edit/delete/16/ HTTP/1.1" 200 642
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[12/Apr/2019 02:17:27] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 52678)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Performing system checks...

System check identified no issues (0 silenced).
April 11, 2019 - 12:49:57
Django version 2.1.8, using settings 'myblog.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[12/Apr/2019 02:26:33] "GET /blog/edit/delete/16/ HTTP/1.1" 200 642
[12/Apr/2019 03:50:27] "GET /blog/index HTTP/1.1" 301 0
[12/Apr/2019 03:50:27] "GET /blog/index/ HTTP/1.1" 200 642
Not Found: /favicon.ico
[12/Apr/2019 03:50:29] "GET /favicon.ico HTTP/1.1" 404 2081
[12/Apr/2019 03:50:31] "GET /blog/article/3/ HTTP/1.1" 200 400
Not Found: /favicon.ico
[12/Apr/2019 03:50:31] "GET /favicon.ico HTTP/1.1" 404 2081
[12/Apr/2019 03:50:41] "GET /blog/edit/ HTTP/1.1" 200 552
Not Found: /favicon.ico
[12/Apr/2019 03:50:41] "GET /favicon.ico HTTP/1.1" 404 2081
Performing system checks...

System check identified no issues (0 silenced).
April 12, 2019 - 02:26:13
Django version 2.1.8, using settings 'myblog.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[12/Apr/2019 13:41:27] "GET /blog/edit/action/ HTTP/1.1" 200 864
[12/Apr/2019 13:41:34] "GET /blog/article/2/ HTTP/1.1" 200 409
[12/Apr/2019 13:41:50] "GET /mooc/show HTTP/1.1" 301 0
[12/Apr/2019 13:41:50] "GET /mooc/show/ HTTP/1.1" 200 168
[12/Apr/2019 13:41:50] "GET /media/img/aa_VmTs3QE.jpg HTTP/1.1" 200 208275
[12/Apr/2019 13:42:07] "GET /admin/ HTTP/1.1" 200 5763
[12/Apr/2019 13:42:07] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[12/Apr/2019 13:42:07] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /admin/mooc/img/ HTTP/1.1" 200 4290
[12/Apr/2019 13:42:09] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[12/Apr/2019 13:42:09] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[12/Apr/2019 13:42:09] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[12/Apr/2019 13:42:22] "POST /admin/mooc/img/ HTTP/1.1" 200 3298
[12/Apr/2019 13:42:22] "GET /static/admin/js/cancel.js HTTP/1.1" 200 410
[12/Apr/2019 13:42:23] "POST /admin/mooc/img/ HTTP/1.1" 302 0
[12/Apr/2019 13:42:24] "GET /admin/mooc/img/ HTTP/1.1" 200 3259
[12/Apr/2019 13:42:24] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[12/Apr/2019 13:42:24] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[12/Apr/2019 14:04:42] "GET /admin/mooc/img/ HTTP/1.1" 200 3140
[12/Apr/2019 14:04:42] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
[12/Apr/2019 14:04:45] "GET /admin/mooc/ HTTP/1.1" 200 2401
[12/Apr/2019 14:04:47] "GET /admin/ HTTP/1.1" 200 6002
[12/Apr/2019 14:05:56] "GET /admin/mooc/img/ HTTP/1.1" 200 3140
[12/Apr/2019 14:05:56] "GET /admin/jsi18n/ HTTP/1.1" 200 3185
Not Found: /
[12/Apr/2019 16:23:27] "GET / HTTP/1.1" 404 2262
----------------------------------------
Exception happened during processing of request from ('101.251.242.238', 46172)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[12/Apr/2019 22:28:07] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 42766)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /http:/www.qq.com/404/search_children.js
[13/Apr/2019 05:21:13] "GET http://www.qq.com/404/search_children.js HTTP/1.1" 404 1723
----------------------------------------
Exception happened during processing of request from ('120.132.3.65', 55840)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[13/Apr/2019 05:21:18] code 400, message Bad request syntax ('\x04\x01\x00PpTi4\x00')
[13/Apr/2019 05:21:18] " PpTi4 " 400 -
[13/Apr/2019 05:21:18] code 400, message Bad request syntax ('\x05\x01\x00')
[13/Apr/2019 05:21:18] " " 400 -
[13/Apr/2019 07:30:52] "GET /blog/index/ HTTP/1.1" 200 864
[13/Apr/2019 07:32:04] "GET /blog/article/17/ HTTP/1.1" 200 263
[13/Apr/2019 07:32:13] "GET /blog/article/17/ HTTP/1.1" 200 263
[13/Apr/2019 07:32:22] "GET /blog/article/12/ HTTP/1.1" 200 342
Not Found: /
[13/Apr/2019 08:12:11] "GET / HTTP/1.0" 404 2272
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[13/Apr/2019 08:34:56] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 52119)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[13/Apr/2019 09:47:04] code 400, message Bad HTTP/0.9 request type ('service')
[13/Apr/2019 09:47:04] "service launcher" 400 -
Not Found: /
[13/Apr/2019 09:47:05] "GET / HTTP/1.0" 404 2272
Not Found: /
[13/Apr/2019 09:47:05] "GET / HTTP/1.0" 404 2262
Not Found: /
[13/Apr/2019 09:47:06] "GET / HTTP/1.1" 404 2262
Not Found: /
[13/Apr/2019 10:56:46] "GET / HTTP/1.1" 404 2262
----------------------------------------
Exception happened during processing of request from ('198.108.67.48', 8122)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[13/Apr/2019 15:14:04] code 400, message Bad request syntax ('\x01\x00\x00\x00\x01\x00\x00\x00\x08\x08')
[13/Apr/2019 15:14:04] "      " 400 -
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[13/Apr/2019 18:42:07] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 50355)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[14/Apr/2019 04:11:50] "GET / HTTP/1.1" 404 2262
[14/Apr/2019 04:31:55] "GET /blog/index/ HTTP/1.1" 200 864
Not Found: /favicon.ico
[14/Apr/2019 04:31:55] "GET /favicon.ico HTTP/1.1" 404 2313
[14/Apr/2019 04:32:06] "GET /blog/article/2/ HTTP/1.1" 200 409
[14/Apr/2019 04:32:09] "GET /blog/edit/delete/2/ HTTP/1.1" 200 750
[14/Apr/2019 04:32:11] "GET /blog/edit/delete/3/ HTTP/1.1" 200 636
[14/Apr/2019 04:32:12] "GET /blog/article/17/ HTTP/1.1" 200 263
[14/Apr/2019 04:32:16] "GET /blog/edit/ HTTP/1.1" 200 552
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[14/Apr/2019 04:41:47] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 39375)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[14/Apr/2019 10:54:55] "GET / HTTP/1.1" 404 2257
Not Found: /favicon.ico
[14/Apr/2019 10:54:59] "GET /favicon.ico HTTP/1.1" 404 2313
[14/Apr/2019 14:06:36] "GET /blog/index/ HTTP/1.1" 200 636
Not Found: /favicon.ico
[14/Apr/2019 14:06:37] "GET /favicon.ico HTTP/1.1" 404 2313
[14/Apr/2019 14:06:40] "GET /blog/article/12/ HTTP/1.1" 200 342
[14/Apr/2019 14:06:45] "GET /blog/index/ HTTP/1.1" 200 636
[14/Apr/2019 14:06:46] "GET /blog/edit/ HTTP/1.1" 200 552
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[14/Apr/2019 14:47:37] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 55346)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[14/Apr/2019 15:18:19] "GET / HTTP/1.0" 404 2272
[14/Apr/2019 15:18:21] code 400, message Bad HTTP/0.9 request type ('l\x00')
[14/Apr/2019 15:18:21] "l          " 400 -
[2019-04-14 15:18:21,711] - Broken pipe from ('45.79.13.120', 34700)

Not Found: /nice ports,/Trinity.txt.bak
[14/Apr/2019 15:18:22] "GET /nice%20ports%2C/Tri%6Eity.txt%2ebak HTTP/1.0" 404 2373
[14/Apr/2019 15:18:23] code 400, message Bad request syntax ('\x05\x04\x00\x01\x02\x80\x05\x01\x00\x03')
[14/Apr/2019 15:18:23] "  " 400 -
[14/Apr/2019 15:18:25] code 400, message Bad request syntax ('\x04\x01\x00\x16\x7f\x00\x00\x01root\x00')
[14/Apr/2019 15:18:25] "   root " 400 -
[2019-04-14 15:18:25,470] - Broken pipe from ('45.79.13.120', 37248)

[14/Apr/2019 15:18:25] code 400, message Bad request syntax ('#ST')
[14/Apr/2019 15:18:25] "#ST" 400 -
[14/Apr/2019 15:18:27] code 400, message Bad HTTP/0.9 request type ('\x00')
[14/Apr/2019 15:18:27] " n    beio" 400 -
[2019-04-14 15:18:27,817] - Broken pipe from ('45.79.13.120', 38898)

[14/Apr/2019 15:18:29] code 400, message Bad request syntax ('\x00\x00\x07\x00\x08\x00\x03\x00\x04\x00\x05\x00\x06')
[14/Apr/2019 15:18:29] "       " 400 -
[2019-04-14 15:18:29,587] - Broken pipe from ('45.79.13.120', 40082)

Not Found: /
[14/Apr/2019 15:18:29] "OPTIONS / HTTP/1.0" 404 2276
[14/Apr/2019 15:18:30] code 400, message Bad request version ('RTSP/1.0')
[14/Apr/2019 15:18:30] "OPTIONS / RTSP/1.0" 400 -
----------------------------------------
Exception happened during processing of request from ('45.79.13.120', 42060)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[14/Apr/2019 15:18:34] code 400, message Bad HTTP/0.9 request type ('\x00')
[14/Apr/2019 15:18:34] "          versionbind   " 400 -
[2019-04-14 15:18:34,392] - Broken pipe from ('45.79.13.120', 43188)

[14/Apr/2019 15:18:36] code 400, message Bad HTTP/0.9 request type ('\x00')
[14/Apr/2019 15:18:36] "            " 400 -
[2019-04-14 15:18:36,233] - Broken pipe from ('45.79.13.120', 44396)

[14/Apr/2019 15:18:36] code 400, message Bad request syntax ('HELP')
[14/Apr/2019 15:18:36] "HELP" 400 -
[14/Apr/2019 15:18:37] code 400, message Bad request syntax ('\x16\x03\x00\x00S\x01\x00\x00O\x03\x00?G×÷º,îê²`~ó\x00ý\x82{¹Õ\x96Èw\x9bæÄÛ<=Ûoï\x10n\x00\x00(\x00\x16\x00\x13\x00')
[14/Apr/2019 15:18:37] You're accessing the development server over HTTPS, but it only supports HTTP.

[14/Apr/2019 15:18:38] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00*%à\x00\x00\x00\x00\x00Cookie:')
[14/Apr/2019 15:18:38] "  *%à     Cookie: mstshash=beio" 400 -
[14/Apr/2019 15:18:38] code 400, message Bad request version ('\x00/\x00')
[14/Apr/2019 15:18:38] You're accessing the development server over HTTPS, but it only supports HTTP.

[14/Apr/2019 15:18:40] code 400, message Bad request syntax ('\x00\x00\x00qj\x81n0\x81k¡\x03\x02\x01\x05¢\x03\x02\x01')
[14/Apr/2019 15:18:40] "   qjn0k¡¢" 400 -
[14/Apr/2019 15:18:42] code 400, message Bad request syntax ('\x00\x00\x00¤ÿSMBr\x00\x00\x00\x00\x08\x01@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x06\x00\x00\x01\x00\x00\x81\x00\x02PC NETWORK PROGRAM 1.0\x00\x02MICROSOFT NETWORKS 1.03\x00\x02MICROSOFT NETWORKS 3.0\x00\x02LANMAN1.0\x00\x02LM1.2X002\x00\x02Samba\x00\x02NT LANMAN 1.0\x00\x02NT LM 0.12\x00')
[14/Apr/2019 15:18:42] "   ¤ÿSMBr    @              @     PC NETWORK PROGRAM 1.0 MICROSOFT NETWORKS 1.03 MICROSOFT NETWORKS 3.0 LANMAN1.0 LM1.2X002 Samba NT LANMAN 1.0 NT LM 0.12 " 400 -
[2019-04-14 15:18:42,081] - Broken pipe from ('45.79.13.120', 49068)

[14/Apr/2019 15:18:42] code 400, message Bad request syntax ('\x01default')
[14/Apr/2019 15:18:42] "default" 400 -
[14/Apr/2019 15:18:43] code 400, message Bad request syntax ('0\x84\x00\x00\x00-\x02\x01\x07c\x84\x00\x00\x00$\x04\x00')
[14/Apr/2019 15:18:43] "0   -c   $ " 400 -
[14/Apr/2019 15:18:45] code 400, message Bad HTTP/0.9 request type ('0')
[14/Apr/2019 15:18:45] "0`  " 400 -
[2019-04-14 15:18:45,105] - Broken pipe from ('45.79.13.120', 51974)

[14/Apr/2019 15:18:45] code 400, message Bad request version ('SIP/2.0')
[14/Apr/2019 15:18:45] "OPTIONS sip:nm SIP/2.0" 400 -
[14/Apr/2019 15:18:47] code 400, message Bad request syntax ('TNMP\x04\x00\x00\x00TNME\x00\x00\x04\x00')
[14/Apr/2019 15:18:47] "TNMP   TNME   " 400 -
[2019-04-14 15:18:47,505] - Broken pipe from ('45.79.13.120', 54084)

[14/Apr/2019 15:18:49] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00')
[14/Apr/2019 15:18:49] "  à     " 400 -
[2019-04-14 15:18:49,378] - Broken pipe from ('45.79.13.120', 55714)

[14/Apr/2019 15:18:51] code 400, message Bad request syntax ('DmdT\x00\x00\x00\x17\x00\x00\x00\x01\x00\x00\x00\x00\x11\x11\x00ÿ\x01ÿ\x13')
[14/Apr/2019 15:18:51] "DmdT           ÿÿ" 400 -
[2019-04-14 15:18:51,156] - Broken pipe from ('45.79.13.120', 57336)

[14/Apr/2019 15:18:52] code 400, message Bad HTTP/0.9 request type (':\x00\x00\x00/\x00\x00\x00\x02\x00\x00@\x02\x0f\x00\x01\x00=\x05\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00/\x00\x00\x00\x00\x00\x00\x00\x00\x00@')
[14/Apr/2019 15:18:52] ":   /     @  =            /         @                 " 400 -
[14/Apr/2019 15:18:54] code 400, message Bad request syntax ('JRMI\x00\x02K')
[14/Apr/2019 15:18:54] "JRMI K" 400 -
[2019-04-14 15:18:54,791] - Broken pipe from ('45.79.13.120', 60452)

[14/Apr/2019 15:18:56] code 400, message Bad request syntax ('\x01\x00\x00ýÎú\x0b°\xa0\x00\x00\x00MMS\x14\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x01\x00\x03\x00ðððð\x0b\x00\x04\x00\x1c\x00\x03\x00N\x00S\x00P\x00l\x00a\x00y\x00e\x00r\x00/\x009\x00.\x00\x00.\x00\x00.\x02\x009\x008\x00\x00;\x00 \x00{\x00\x00\x00\x00\x00A\x00A\x00\x00\x00-\x00\x00A\x00\x00\x00-\x00\x00\x00a\x00\x00-\x00A\x00A\x00\x00A\x00-\x00\x00\x00\x00\x00A\x00\x00A\x00A\x00\x00A\x00A\x00\x00}\x00\x00\x00àmß_')
[14/Apr/2019 15:18:56] "  ýÎú°    MMS                    ðððð    N S P l a y e r / 9 .  .  . 9 8  ;   {     A A   -  A   -   a  - A A  A -     A  A A  A A  }   àmß_" 400 -
[2019-04-14 15:18:56,527] - Broken pipe from ('45.79.13.120', 33760)

[14/Apr/2019 15:18:58] code 400, message Bad HTTP/0.9 request type ('\x00Z\x00\x00\x01\x00\x00\x00\x016\x01,\x00\x00\x08\x00\x7fÿ\x7f\x08\x00\x00\x00\x01\x00')
[14/Apr/2019 15:18:58] " Z     6,   ÿ      :               æ           (CONNECT_DATA=(COMMAND=version))" 400 -
[2019-04-14 15:18:58,302] - Broken pipe from ('45.79.13.120', 35176)

----------------------------------------
Exception happened during processing of request from ('45.79.13.120', 36576)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[14/Apr/2019 15:19:01] code 400, message Bad request syntax ('\x00\x03\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x0f\x00')
[14/Apr/2019 15:19:01] "              " 400 -
[2019-04-14 15:19:01,951] - Broken pipe from ('45.79.13.120', 37886)

[14/Apr/2019 15:19:03] code 400, message Bad request syntax ('GIOP\x01\x00\x01\x00$\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x06\x00\x00\x00abcdef\x00\x00\x04\x00\x00\x00get\x00\x00\x00\x00\x00')
[14/Apr/2019 15:19:03] "GIOP  $                abcdef     get     " 400 -
[2019-04-14 15:19:03,769] - Broken pipe from ('45.79.13.120', 39190)

[14/Apr/2019 15:19:06] code 400, message Bad request syntax ('\x00\x9c\x00\x01\x1a+<M\x00\x01\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01ÿÿ\x00\x01none\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00beio\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
[14/Apr/2019 15:19:06] "  +<M            ÿÿ none                                                            beio                                                            " 400 -
[2019-04-14 15:19:06,577] - Broken pipe from ('45.79.13.120', 40460)

[14/Apr/2019 15:19:09] code 400, message Bad request syntax ('\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x01\x00\x00\x00\x00')
[14/Apr/2019 15:19:09] "                   " 400 -
[2019-04-14 15:19:09,416] - Broken pipe from ('45.79.13.120', 42282)

[14/Apr/2019 15:19:11] code 400, message Bad request syntax ('\x03\x81\x00\x00\x00\x00\x00_@\x00\x017\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00InitiatorName=iqn.1991-05.com.microsoft:beio-iscsi-probe\x00SessionType=Discovery\x00AuthMethod=None\x00\x00')
[14/Apr/2019 15:19:11] "     _@ 7                                InitiatorName=iqn.1991-05.com.microsoft:beio-iscsi-probe SessionType=Discovery AuthMethod=None  " 400 -
[2019-04-14 15:19:11,168] - Broken pipe from ('45.79.13.120', 44154)

[14/Apr/2019 15:19:12] code 400, message Bad request syntax ('\x01\x00\x00\x00\x00Í\x00\x01\x00\x00ANY-SCP\x00\x00\x00\x00\x00\x00\x00\x00\x00FINDSCU\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x151.2.840.10008.3.1.1.1 \x00\x00.\x01\x00\x00\x000\x00\x00\x111.2.840.10008.1.1@\x00\x00\x111.2.840.10008.1.2P\x00\x00:Q\x00\x00\x04\x00\x00@\x00R\x00\x00\x1e1.2.826.0.1.3680043.2.1396.999U\x00\x00\x0cCharruaVista')
[14/Apr/2019 15:19:12] "    Í   ANY-SCP         FINDSCU                                           1.2.840.10008.3.1.1.1   .   0  1.2.840.10008.1.1@  1.2.840.10008.1.2P  :Q    @ R  1.2.826.0.1.3680043.2.1396.999U  CharruaVista" 400 -
----------------------------------------
Exception happened during processing of request from ('159.203.169.16', 51081)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 169, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
Not Found: /
[14/Apr/2019 22:44:45] "GET / HTTP/1.1" 404 2263
Not Found: /http:/www.baidu.com/cache/global/img/gs.gif
[15/Apr/2019 00:54:47] "GET http://www.baidu.com/cache/global/img/gs.gif HTTP/1.1" 404 1738
----------------------------------------
Exception happened during processing of request from ('80.82.70.187', 38872)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 636, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 358, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 692, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 171, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/local/lib/python3.6/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
[15/Apr/2019 01:37:56] "GET /blog/index HTTP/1.1" 301 0
[15/Apr/2019 01:37:56] "GET /blog/index/ HTTP/1.1" 200 636
Not Found: /favicon.ico
[15/Apr/2019 01:37:56] "GET /favicon.ico HTTP/1.1" 404 2313
[15/Apr/2019 01:38:06] "GET /blog/article/12/ HTTP/1.1" 200 342
Not Found: /favicon.ico
[15/Apr/2019 01:38:06] "GET /favicon.ico HTTP/1.1" 404 2313
[15/Apr/2019 01:38:13] "GET /blog/article/17/ HTTP/1.1" 200 263
Not Found: /favicon.ico
[15/Apr/2019 01:38:13] "GET /favicon.ico HTTP/1.1" 404 2313
[15/Apr/2019 01:39:05] "GET /mooc/show HTTP/1.1" 301 0
[15/Apr/2019 01:39:05] "GET /mooc/show/ HTTP/1.1" 200 123
Not Found: /favicon.ico
[15/Apr/2019 01:39:05] "GET /favicon.ico HTTP/1.1" 404 2313
[15/Apr/2019 02:04:03] "GET /blog/index/ HTTP/1.1" 200 650
Not Found: /favicon.ico
[15/Apr/2019 02:04:03] "GET /favicon.ico HTTP/1.1" 404 2313
[15/Apr/2019 02:04:07] "GET /blog/index/ HTTP/1.1" 200 650
[15/Apr/2019 02:05:05] "GET /blog/edit/ HTTP/1.1" 200 552
[15/Apr/2019 02:07:05] "POST /blog/edit/action/ HTTP/1.1" 200 782
[15/Apr/2019 02:07:07] "GET /blog/article/18/ HTTP/1.1" 200 394
[15/Apr/2019 02:07:09] "GET /blog/edit/tocha/18/ HTTP/1.1" 200 698
[15/Apr/2019 02:07:16] "GET /blog/index/ HTTP/1.1" 200 782
[15/Apr/2019 02:07:18] "GET /blog/article/17/ HTTP/1.1" 200 263
[15/Apr/2019 02:07:21] "GET /blog/edit/ HTTP/1.1" 200 552
[15/Apr/2019 02:13:04] "GET /blog/index/ HTTP/1.1" 200 884
